#!/bin/bash
TARGET="$HOME/Jagex/launcher"
TFILE="/splash6.gif"
RESULT=0

# START APPLESCRIPT NONSENSE
function bad_gif
{
  if [ $# -eq 0 ]; then
  /usr/bin/osascript <<-EOF
    tell application "System Events"
      activate
      display dialog "THAT WASN'T ACTUALLY A .gif FILE!\n\nTry again."\
      default button 1 buttons {"Sorry!"}

      if button returned of result is "Sorry!" then
        return
      end if
    end tell
EOF
fi
}

if [ $# -eq 0 ]; then
RESULT=`/usr/bin/osascript <<-EOF
  tell application "System Events"
    activate
    display dialog "THAT IS NOT HOW THIS WORKS.\n\nPlease drag a *.gif file into this applet."\
    default button 1 buttons {"Oh, okay"}

    if button returned of result is "Oh, okay" then
      return 0
    end if
  end tell
EOF`
  # The user is obeying me! Save his choice!
else
RESULT=`/usr/bin/osascript <<-EOF
  tell application "System Events"
    activate
    display dialog "You are about to replace the RuneScape NXT loading image.\
    \n\nAre you sure you want to do that?"\
    default button 2 buttons {"Go ahead!", "WAIT NO STOP!"}
    if button returned of result is "Go ahead!" then
      return 1
    else if button returned of result is "WAIT NO STOP!" then
      return 0
    end if
    end tell
EOF`
fi
# END APPLESCRIPT NONSENSE

CANRUN=0
UINPUT="$1"
echo $UINPUT

if [ "$RESULT" -eq 0 ]; then
  echo "Cancel..."
  exit
else
  echo "Half-assing file verification..."
  # Do you really think I'm going to check the actual binary data itself?
  if [ ${UINPUT: -4} == ".gif" ] || [ ${UINPUT: -4} == ".GIF" ]; then
    echo "Hopefully definitely a .gif file..."
    eval rm "$TARGET$TFILE" #"~/Jagex/launcher/splash6.gif"
    eval cp "\"$UINPUT\" \"$TARGET\"\"$TFILE\""
  else
    bad_gif #see top of file, local function call
  fi
fi

echo "Done..."